# Generated by Django 3.2.16 on 2025-02-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20250206_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='cteated_at',
            new_name='created_at',
        ),
    ]
